#!/bin/bash

if ! command -v pio >/dev/null 2>&1; then
    echo "PlatformIO is not installed. Please install PlatformIO to run the linter." >&2
    exit 1
fi

pio check --fail-on-defect high
rc=$?

if [ $rc -ne 0 ]; then
    exit $rc
fi

echo $@
